export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CHECK_AUTH = 'CHECK_AUTH';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const REQUEST_OFFERS = 'REQUEST_OFFERS';
export const RECEIVE_OFFERS = 'RECEIVE_OFFERS';
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const CHECKED_ANSWER = 'CHECKED_ANSWER';

// Auth0 Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const NO_SUBMITTED = 'NO_SUBMITTED';
export const SUBMITTED_SUCCESS = 'SUBMITTED_SUCCESS';
export const UPDATED_ANSWER = 'UPDATED_ANSWER';

export const SET_SUBMIT_SUCCEEDED = '@@redux-form/SET_SUBMIT_SUCCEEDED';

